<a href="https://colab.research.google.com/github/bigswot/courseragitexercise/blob/Child_branch/00_tensorflow_dundatments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundmental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Get info from tensors
* manipulate tensors
* Tensors and NumPy
* Using @ts.function (a way to speed up regular Python functions)
* using GPUs with Tensorflow (or tpus)
* Exercises to try


## Introduction to Tensors

In [32]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [21]:
# create a vector
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [6]:
# check the dimension of the vector

vector.ndim

1

In [7]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [14]:
# Create matrix 

another_matrix=tf.constant([[10,7],
                           [3.,2.],
                           [8.,9.]],
                           dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [18]:
# create a tensor

tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
tensor.ndim

3

What we've created so far:

* scalar: single number
* vector: number with direction
* matrix: a 2 dimenional array of numbers
* tensor: an n-dimensional array of numbers( where n can be any number, a 0-dimensional tensor is a scalar, 1 dimensional tensor is a vector)


# Creating tensors with tf.Variable



In [22]:
# create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# try change one of the elements in the changeable tensor
changeable_tensor[0].assign( 7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [31]:
# try change the unchangeable tensor
unchangeable_tensor[0].assign(7)


AttributeError: ignored